// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhHESvhCivvA_raxL48EdCizCNMzgcpt0',
    appId: '1:518037691020:web:2b9454c525beb582bcb9a9',
    messagingSenderId: '518037691020',
    projectId: 'projectkb-61603',
    authDomain: 'projectkb-61603.firebaseapp.com',
    storageBucket: 'projectkb-61603.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjO68Nqg4mtbTFmlYYdl7wRboDwGqJJDs',
    appId: '1:518037691020:android:2d111e10e2a2536bbcb9a9',
    messagingSenderId: '518037691020',
    projectId: 'projectkb-61603',
    storageBucket: 'projectkb-61603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMPVmfDobDcfoGUVOqEsbpyUZZcvi0b1c',
    appId: '1:518037691020:ios:62af07ac7ed98b3bbcb9a9',
    messagingSenderId: '518037691020',
    projectId: 'projectkb-61603',
    storageBucket: 'projectkb-61603.appspot.com',
    iosClientId: '518037691020-70j7k7h8lugbaegtqrbhcmc8nr66072a.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAmbw',
  );
}
